### PR TITLE
Location Aware

### PR DESCRIPTION
**Pull request by jamierytlewski**
I have added some code to check your location whenever it does the update.

### CODE REVIEW

**Comment by jamierytlewski** [comment]
I'm really new to Git and GitHub, so I probably screwed this pull request up.

**Comment by metawatchclient** [comment]
I am new also, but I think you only need to start pull request for cc84e4c5f26c48da9327b3a72c77b1db94ba8f6e, no others.

**Comment by jamierytlewski** [comment]
Yeah, I'm going to have to look at it later...I keep getting a merge conflict with MWWeatherMonitor.m file and I have to figure out why.

**Comment by metawatchclient** [comment]
Added auto location changes detection for retrieving the weather.

**Pull request closed without merging**
