### PR TITLE
Misspelling on the TestViewController.xib

### PR DESCRIPTION
**Pull request by jamierytlewski**
decrease was spelled drcrease

### CODE REVIEW

**Comment by metawatchclient** [comment]
Sry, I just saw your request today.... Can you make a new pull request? I will try to merge it.

**Comment by jamierytlewski** [comment]
Actually it looks to be fixed already.

**Comment by metawatchclient** [comment]
You mean the misspelling?

What about the location feature?

**Comment by jamierytlewski** [comment]
Yeah, the misspelling is fixed. I'll make a pull request for the location. I'm not sure how optimized it is though. It only checks your location when it does an update. So I have my watch update me every 30 minutes and every 30 minutes as it's checking your location. I wanted to try and make it changed based on when you move a certain distance, I just haven't been able to figure that out yet.

**Pull request closed without merging**
